/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "push_server_constants.h"

namespace tis {

const push_serverConstants g_push_server_constants;

push_serverConstants::push_serverConstants() {
}

} // namespace

