/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef push_server_CONSTANTS_H
#define push_server_CONSTANTS_H

#include "push_server_types.h"

namespace tis {

class push_serverConstants {
 public:
  push_serverConstants();

};

extern const push_serverConstants g_push_server_constants;

} // namespace

#endif
