/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "system_message_constants.h"

namespace tis {

const system_messageConstants g_system_message_constants;

system_messageConstants::system_messageConstants() {
}

} // namespace

