/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef system_message_CONSTANTS_H
#define system_message_CONSTANTS_H

#include "system_message_types.h"

namespace tis {

class system_messageConstants {
 public:
  system_messageConstants();

};

extern const system_messageConstants g_system_message_constants;

} // namespace

#endif
